# zsh configuration
ZSH_THEME="spaceship"

SPACESHIP_BATTERY_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_EXEC_TIME_SHOW=false
SPACESHIP_GIT_SYMBOL=
SPACESHIP_GRADLE_SHOW=false
SPACESHIP_HG_SHOW=false
SPACESHIP_HOST_SHOW=false
SPACESHIP_MAVEN_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_RUBY_SHOW=false

# config
export DOTFILES_REMOTE="$DOTFILES/extensions/remote"
export DOTFILES_REMOTE_ZSH="$DOTFILES_REMOTE/zsh"

source "$DOTFILES_REMOTE_ZSH/.bootstrap"
